name: Publish 
run-name: ${{ github.actor }} - Publish 
on: 
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/tests.yml
  deploy:
    name: publishing
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          python -m pip install build twine
          python -m build
          python -m twine upload dist/* --skip-existing