name: Publish 
run-name: ${{ github.actor }} - Publish 
on: 
  release: 
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/tests.yml
  deploy:
    name: publishing
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Build distributions
        run: |
          python -m pip install build twine
          python -m build
  
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TWINE_PASSWORD}}