name: Publish 
run-name: ${{ github.actor }} - Publish 
on: 
  push:
    tags:
      - '*'

jobs:
  test:
    uses: ./.github/workflows/tests.yml
  deploy:
    name: publishing
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Build distributions
        run: |
          python pip install build twine
          python -m build
  
      - name: Publish package to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TWINE_PASSWORD}}