# Create GH Action to run pytest

name: Tests
run-name: ${{ github.actor }} - PyTest
on: [pull_request, workflow_call]

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
           python-version: "3.11"
      - run: |
          pip install -r requirements.txt
          python -m pytest
